spring:
  application:
    name: eureka-server-app
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    instance:
      hostname: localhost
---
server:
  port: 8080
eureka:
  server:




