spring:
  profiles: dev
  application:
    name: transactions-app
#  cloud:
#    config:
#      server:
#        git:
#          basedir: target/config
#          uri: https://github.com/shinebar/config-repo

server:
  port: 8001
eureka:
  instance:
    appname: transactions-app
#    hostname: http://localhost:8080
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka/