spring:
  application:
    name: transactions-app
server:
  port: 8001
eureka:
  instance:
    appname: transactions-app
#    hostname: http://localhost:8080
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka/